### ISSUE TITLE
Updated USWDS Community Theme - v1.4.0-rc1 (release candidate 1) Observations in OGP Apps

### ISSUE THREAD

**Issue by radhika-y7** [GSA/uswds-sf-lightning-community#103]
During our review of the Updated USWDS Community Theme - v1.4.0-rc1 in the lower sandbox  (FL1) environment, we observed formatting differences, specifically an increased indention or placement of the Logo/Title in the Production and Sandbox environments.  Please see the following notes and observations for PPRT ,FAIRS and Travel applications that were reviewed:

[**PPRT Application**](https://docs.google.com/document/d/1SoMIVL3KgGL5SNL0xO4fH9j1ePaVzaKqGOYVydfC2ck/edit)

[**FAIRS Application**](https://docs.google.com/document/d/1g-k32gH0Xytc98dkilBaVLpxswgcYS9xohBBAZmU4Yo/edit)

[**TRAVEL Application**](https://docs.google.com/document/d/1FwHrTN6XLsarrI_bbqq8Ok25kbxGKdxn9C2QdrYhA6Q/edit)

**Comment by mvogelgesang** [comment]
Issue resolved by adjusting [Body Width](https://github.com/GSA/uswds-sf-lightning-community/wiki/Theme-Settings#body-width) attribute
