### ISSUE TITLE
'Visit homepage' button on 404 template lightning component not working

### ISSUE THREAD

**Issue by smithaunnivelan** [GSA/uswds-sf-lightning-community#109]
**Describe the bug**

The 'Visit homepage' button on the '404 template - USWDS' lightning component is not working.
**To Reproduce**

1. Go to Experience Builder
2. Open the Error page
3. Drag and drop '404 template - USWDS' lightning component
4. Set attributes for the component
5. Publish
6. Open the site and load the error page
7. Click the button 'Visit homepage'
8. It doesn't take you to the home page and there is no attribute to set the home page URL.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mvogelgesang** [comment]
@smithaunnivelan thanks for posting, will take a look

**Comment by mvogelgesang** [comment]
Verified in 1.4.0, will be posting patch
