### ISSUE TITLE
Minor footer issues

### ISSUE THREAD

**Issue by LittleBigAl** [GSA/uswds-sf-lightning-community#20]
**Please address the following issues with the default footer template (see attached):

- About, Accessibility, FOIA, and Privacy Policy hypertext links do not display the same characteristic browser behavior as one hovers over the links.  Not congruent with the other URL's that may be included.

- Official GSA logo should have a transparent background.

![footer](https://user-images.githubusercontent.com/18166369/88952835-f7d9d700-d265-11ea-8f88-a358dc8ac1e4.PNG)
**

**Comment by mvogelgesang** [comment]
thanks @LittleBigAl these are both solid points. Updates that are forthcoming in #9 will address the first bullet by adding a "pointer" cursor when hovering on links. Second bullet is addressable by site maintainers and has been updated on the labs.gsa.gov site.
