### ISSUE TITLE
Multi-level navigation menus not displaying correctly when mixed with single level menus

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/uswds-sf-lightning-community#9]
**Describe the bug**
When constructing a multi-level navigation menu, it does not display correctly in the Footer Main Nav section. Screenshot below shows the same menu, in the footer with differing results.
![image](https://user-images.githubusercontent.com/4053083/87071919-f11cee80-c1e8-11ea-9acb-40623cdeb09a.png)

**To Reproduce**

1. create a new navigation menu with multiple levels (sub-items)
- Label A
    - Sub Item A
    - Sub Item B
- Single Level Link A
- Single Level Link B

1. Make all links public 
1. Publish

**Expected behavior**
The navigation menu as output in the footer should support menu items with sub-menu's and those without

**Screenshots**
see above

**Comment by mvogelgesang** [comment]
The Footer Nav Menu component is not coded to handle single-level navigation menus and assumes multi-level menu's across the board. Looking at USWDS examples, the two types are not mixed https://designsystem.digital.gov/components/footer/. 

Path forward
- Provide the ability to toggle between different footer navigation menu layouts (Big and Medium) depending on need.

**Comment by mvogelgesang** [comment]
Toggling between different footer navigation menu layouts starts to add complexity to the site builder experience. A couple of other options:

A) move secondary navigation below logo and contact info. The secondary footer nav section was created to support the "boilerplate" links that all sites must have (FOIA, Privacy Policy, etc). Doing so would require an update to the `uswdsFooterNavMenuSmall` component to allow users to left, right, or center justify the menu.  The section on the far right could remain an open drop zone to place email signup or other component.
![image](https://user-images.githubusercontent.com/4053083/89961337-65dfb000-dc0f-11ea-980a-336ddb4e2721.png)

B) The drop zone above has a limited width. The other option may be to extend the main footer menu to be full width with a toggle-able drop zone that is also full width. Move the existing drop zone down the page and make each section there 1/3 width.
![image](https://user-images.githubusercontent.com/4053083/89961582-1ea5ef00-dc10-11ea-84f2-c4ed80bcbda7.png)

**Comment by mvogelgesang** [comment]
positive comments on option B from biz line.

**Comment by carchiere** [comment]
I agree and like option 2 as well.  The footer between the logo and Contact Us has a lot of empty space to use whereas the main footer nav should use the full width.

**Comment by mvogelgesang** [comment]
Features

- [ ] toggle section to right of "Contact Us" that opens up a component drop zone
- [ ] Ability to switch between "Big" and "Small" menu types in Footer Navigation Menu Type attribute
- [ ] Footer Secondary Nav Menu Name moved to bottom of footer and setup for horizontal alignment
- [ ] `uswdsFooterNavMenuSmall` updated to allow for menu to be right, left, and center justified.

Testing Instructions

**Comment by mvogelgesang** [comment]
tested against refreshed sandbox containing an existing community, works as expected. Ready for merge
